title: "Atoms/Button"
description:
  component: "Use Bootstrap custom button styles for actions in forms, dialogs, and more with support for multiple sizes, states, and more."
## Canvas height
height: 150
## Color settings
color:
  description: Bootstrap class
  table:
    category: settings
  default: primary
  options:
    'Primary': 'primary'
    'Secondary': 'secondary'
    'Success': 'success'
    'Danger': 'danger'
    'Warning': 'warning'
    'Info': 'info'
    'Dark': 'dark'
    'Light': 'light'
    'Link': 'link'
## Outline button settings
outline:
  description: boolean
  default: false
  table:
    category: settings
## Size settings
size:
  description: Bootstrap class
  table:
    category: settings
  default: ''
  options:
    Default: ''
    Small: btn-sm
    Large: btn-lg
## Disabled button settings
disabled:
  description: boolean
  default: false
  table:
    category: settings
## Content settings.
content:
  description: string
  default: 'Button'
  table:
    category: fields