title: "Organisms/Footer"
description:
  component: "Footer component description"
## Canvas height
height: 150
## Container settings
container:
  description: 'id'
  table:
    category: 'settings'
  default: 'container'
  options:
    'Container': 'container'
    'Fluid': 'container-fluid'
## Nav Items
items:
  item1:
    title: 'Link'
    url: '/'
  item2:
    title: 'Link'
    url: '/'
  item3:
    title: 'Link'
    url: '/'
  item4:
    title: 'Link'
    url: '/'