title: "Templates/3 Columns Layout"
description:
  component: "3 column layout component."
## Canvas height
height: 200
## row settings
row:
  description: boolean
  default: true
  table:
    category: fields
## Column settings
container:
  description: boolean
  default: true
  table:
    category: fields
## Column 1 content settings.
column_1_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 2 content settings.
column_2_content:
  description: string
  default: "string"
  table:
    category: fields
## Column 3 content settings.
column_3_content:
  description: string
  default: "string"
  table:
    category: fields
## Desktop (lg) columns size settings.
desktop_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-4"
  options:
    "33% - 33% - 33%": "33_33_33"
    "50% - 25% - 25%": "50_25_25"
    "25% - 50% - 25%": "25_50_25"
    "25% - 25% - 50%": "25_25_50"
## Tablet (md) columns size settings.
tablet_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-4"
  options:
    "33% - 33% - 33%": "33_33_33"
    "100% - 100% - 100%": "100_100_100"
## Mobile (sm) columns size settings.
mobile_columns_size:
  description: "Bootstrap grid classes"
  table:
    category: "settings"
  default: "col-12"
  options:
    "100% - 100% - 100%": "100_100_100"
