title: "Atoms/Form"
description:
  component: "Give textual form controls <input>s an upgrade with custom styles, sizing, focus states, and more."
## Canvas height
height: 150
## Size settings
size:
  description: Bootstrap class
  table:
    category: settings
  default: ''
  options:
    Default: ''
    Small: form-control-sm
    Large: form-control-lg
## Form control class settings
form_control:
  description: boolean
  default: true
  table:
    category: 'settings'