- upgrade_d7_taxonomy_vocabulary
- upgrade_taxonomy_settings
- upgrade_d7_taxonomy_term_tags
- upgrade_d7_taxonomy_term_regions
- upgrade_d7_taxonomy_term_project_status
- upgrade_d7_taxonomy_term_nations
- upgrade_d7_taxonomy_term_translation_status
- upgrade_d7_taxonomy_term_transcription_status
- upgrade_d7_taxonomy_term_text_type
- upgrade_d7_taxonomy_term_record_status
- upgrade_d7_taxonomy_term_local_origin
- upgrade_d7_taxonomy_term_languages
- upgrade_d7_taxonomy_term_language_item_source
- upgrade_d7_taxonomy_term_institution
- upgrade_d7_taxonomy_term_item_type
- upgrade_d7_taxonomy_term_interpretation
- upgrade_d7_taxonomy_term_folders
- upgrade_d7_taxonomy_term_exchange_types
- upgrade_d7_taxonomy_term_contributors
- upgrade_d7_taxonomy_term_contributor_roles
- upgrade_d7_taxonomy_term_collection
