title: "Organisms/Form/Input"
description:
  component: "Give textual form controls <input>s an upgrade with custom styles, sizing, focus states, and more."
## Canvas height
height: 150
## Size settings
size:
  description: Bootstrap class
  table:
    category: settings
  default: ''
  options:
    Default: ''
    Small: form-control-sm
    Large: form-control-lg
## Placeholder input settings
placeholder:
  description: string
  default: ''
  table:
    category: settings
## Disabled input settings
disabled:
  description: boolean
  default: false
  table:
    category: settings