title: "Molecules/ListGroup"
description:
  component: "List group component description"
## Canvas height.
height: 150
## List tag settings
tag:
  description: Bootstrap class
  table:
    category: fields
  default: 'default'
  options:
    'Unordered list': 'ul'
    'Numbered': 'ol'
## Flush settings
flush:
  description: boolean
  default: false
  table:
    category: settings
## Horizontal settings
horizontal:
  description: boolean
  default: false
  table:
    category: settings
## Items background color settings
items_bg_color:
  description: Bootstrap class
  table:
    category: settings
  default: ''
  options:
    'Default': ''
    'Primary': 'primary'
    'Secondary': 'secondary'
    'Success': 'success'
    'Danger': 'danger'
    'Warning': 'warning'
    'Info': 'info'
    'Dark': 'dark'
    'Light': 'light'
    'Link': 'link'
## Items settings
items:
  item1:
    text: 'First item'
  item2:
    text: 'Second item'
  item3:
    text: 'Third item'
  item4:
    text: 'Fourth item'
  item5:
    text: 'Fifth item'