title: "Atoms/Badge"
description:
  component: "Documentation and examples for badges, our small count and labeling component."
## Canvas height
height: 150
## Color settings
color:
  description: Bootstrap text and background class
  table:
    category: settings
  default: text-bg-primary
  options:
    'Primary': 'text-bg-primary'
    'Secondary': 'text-bg-secondary'
    'Success': 'text-bg-success'
    'Info': 'text-bg-info'
    'warning': 'text-bg-warning'
    'Danger': 'text-bg-danger'
    'Light': 'text-bg-light'
    'Dark': 'text-bg-dark'
## Padge HTML tag settings.
tag:
  description: HTML tag for padge
  table:
    category: settings
  default: 'span'
  options:
    'Span': 'span'
    'Link': 'a'
    'Div': 'div'
## Content settings.
content:
  description: string
  default: 'Badge'
  table:
    category: fields
## Content settings.
url:
  description: string
  default: ''
  table:
    category: fields